name: Update POM dependency version

on: 
  pull_request:
    branches: [ "" ]
  workflow_dispatch:
    inputs:
      artifactId:
        description: 'artifactId to update'
        default: 'spring-boot-starter-test'
      desiredArtifactIdVersion:
        description: 'version to be updated to'
        default: '1.2.3'
env:
  POM_FILE: "./complete/pom.xml"
  TMP_FILE: "./complete/tmp.json"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Step 1: Create JSON version of POM.XML to work with jq
    - name: tmp json of pom.xml
      uses: mikefarah/yq@master
      with:
        cmd: yq --input-format xml --output-format json $POM_FILE > $TMP_FILE
    
    #- name: value of tmp.json
    #  run: cat $TMP_FILE
    #  shell: bash
     
    # Step 2: Get indexOf of artifactId
    - name: Get index artifactId
      uses: sergeysova/jq-action@v2
      id: index
      with:
        cmd: 'jq -r ".project.dependencies.dependency | .[map(select(.artifactId == \"${{ inputs.artifactId }}\"))][0]" $TMP_FILE'
        multiline: true
        
    # Step 3: Get current version of artifactId
    - name: Get current version
      uses: sergeysova/jq-action@v2
      id: currentVersion
      with:
        cmd: 'jq -r ".project.dependencies.dependency[${{ steps.index.outputs.value }}].version" $TMP_FILE'
        
    # Step 4: Update version if desiredVersion != currentVersion and store it in tmp.json
    - name: Update version in tmp
      if: ${{ steps.currentVersion.outputs.value }} != ${{ inputs.desiredArtifactIdVersion }}
      id: updateVersion
      uses: sergeysova/jq-action@v2
      with:
        cmd: 'echo $(jq -r ".project.dependencies.dependency[${{ steps.index.outputs.value }}].version |= \"${{ inputs.desiredArtifactIdVersion }}\"" $TMP_FILE) > $TMP_FILE'
   
   # Step 5: Update POM.XML
    - name: Update POM
      id: updatePOM
      if: ${{ steps.updateVersion }}
      uses: mikefarah/yq@master
      with:
        cmd: yq --input-format json --output-format xml $TMP_FILE > $POM_FILE
        
    - name: delete unnecesary files
      run: rm $TMP_FILE
      shell: bash
      
    #  Step 5.1: Create pull request
    - name: Create Pull Request
      if: ${{ steps.updatePOM }}
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update POM dependency version
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: main
        delete-branch: false
        title: '[Automated] ${{ inputs.artifactId }}  ${{ steps.currentVersion.outputs.value }} -> ${{ inputs.desiredArtifactIdVersion }}'
        body: |
          Update report
          - artifactId: ${{ inputs.artifactId }}
          - artifactVersion: ${{ inputs.desiredArtifactIdVersion }}
        labels: |
          automated pr
     #  Step 5.2: Notify via <teams,slack>
    - uses: actions/checkout@master
  success:
    needs: build
    name: MS Teams Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ${{ inputs.artifactId }}  ${{ steps.currentVersion.outputs.value }} -> ${{ inputs.desiredArtifactIdVersion }}
        uses: skitionek/notify-microsoft-teams@master
        # if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          #raw: >-
          #  {
          #    "@type": "MessageCard",
          #    "@context": "http://schema.org/extensions",
          #    "title": "No ${variables} avaliable in here"
          #  }
