
name: Update POM dependency version

on:
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      artifactId:
        description: 'artifactId to update'
        default: 'spring-boot-starter-test'
      desiredArtifactIdVersion:
        description: 'version to be updated to'
        default: '1.2.3'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get index artifactId
      uses: sergeysova/jq-action@v2
      id: index
      with:
        cmd: 'jq -r ".project.dependencies.dependency | .[map(select(.artifactId == \"${{ inputs.artifactId }}\"))][0]" ./complete/file.json'
        multiline: true
   
    - name: Compare currentVersion vs desiredVersion
      uses: sergeysova/jq-action@v2
      id: currentVersion
      with:
        cmd: 'jq -r ".project.dependencies.dependency[${{ steps.index.outputs.value }}].version" ./complete/file.json'
    - name: Update version
      if: ${{ steps.currentVersion.outputs.value }} != ${{ inputs.desiredArtifactIdVersion }}
      id: updateVersion
      uses: sergeysova/jq-action@v2
      with:
        cmd: 'echo $(jq -r ".project.dependencies.dependency[${{ steps.index.outputs.value }}].version |= \"${{ inputs.desiredArtifactIdVersion }}\"" ./complete/file.json) > new.json'
    - name: Update POM
      uses: mikefarah/yq@master
      with:
        cmd: yq --input-format json --output-format xml new.json > ./complete/pom.xml

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update POM dependency version
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: main
        delete-branch: false
        title: '[Automated] Changes to POM.XML'
        body: |
          Update report
          - artifactId: ${{ inputs.artifactId }}
          - artifactVersion: ${{ inputs.desiredArtifactIdVersion }}
        labels: |
          automated pr

