
name: Update POM dependency version

on:
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      artifactId:
        description: 'artifactId to update'
        default: 'spring-boot-starter-test'
      desiredArtifactIdVersion:
        description: 'version to be updated to'
        default: '1.2.3'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Step 1: Create JSON version of POM.XML to work with jq
    - name: tmp json of pom.xml
      uses: mikefarah/yq@master
      with:
        cmd: yq --input-format xml --output-format json pom.xml > ./complete/tmp.json
     
    # Step 2: Get indexOf of artifactId
    - name: Get index artifactId
      uses: sergeysova/jq-action@v2
      id: index
      with:
        cmd: 'jq -r ".project.dependencies.dependency | .[map(select(.artifactId == \"${{ inputs.artifactId }}\"))][0]" ./complete/tmp.json'
        multiline: true
        
    # Step 3: Get current version of artifactId
    - name: Get current version
      uses: sergeysova/jq-action@v2
      id: currentVersion
      with:
        cmd: 'jq -r ".project.dependencies.dependency[${{ steps.index.outputs.value }}].version" ./complete/tmp.json'
        
    # Step 4: Update version if desiredVersion != currentVersion and store it in tmp.json
    - name: Update version in tmp
      if: ${{ steps.currentVersion.outputs.value }} != ${{ inputs.desiredArtifactIdVersion }}
      id: updateVersion
      uses: sergeysova/jq-action@v2
      with:
        cmd: 'echo $(jq -r ".project.dependencies.dependency[${{ steps.index.outputs.value }}].version |= \"${{ inputs.desiredArtifactIdVersion }}\"" ./complete/tmp.json) > ./completed/tmp.json'
   
   # Step 5: Update POM.XML
    - name: Update POM
      id: updatePOM
      if: ${{ steps.updateVersion }}
      uses: mikefarah/yq@master
      with:
        cmd: yq --input-format json --output-format xml tmp.json > ./complete/pom.xml
        
    - name: delete unnecesary files
      run: rm ./completed/tmp.json
      shell: bash
      
    #  Step 5.1: Create pull request
    - name: Create Pull Request
      if: ${{ steps.updatePOM }}
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update POM dependency version
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: main
        delete-branch: false
        title: '[Automated] Changes to POM.XML'
        body: |
          Update report
          - artifactId: ${{ inputs.artifactId }}
          - artifactVersion: ${{ inputs.desiredArtifactIdVersion }}
        labels: |
          automated pr
     #  Step 5.2: Notify via <teams,slack>
    #- name: Notify
    #  id: notify
    #  if: ${{ steps.cpr }}
      
