# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Update POM dependency version

on:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      artifactId:
        description: 'artifactId to update'
        default: 'spring-boot-starter-test'
      desiredArtifactIdVersion:
        description: 'version to be updated to'
        default: '1.2.3'
      #logLevel:
      #  description: 'Log level'
      #  required: true
      #  default: 'warning'
      #  type: choice
      #  options:
      #  - info
      #  - warning
      #  - debug
      #tags:
      #  description: 'Test scenario tags'
      #  required: false
      #  type: boolean
      #environment:
      #  description: 'Environment to run tests against'
      #  type: environment
       # required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Make changes to pull request here
    - name: Get index artifactId
      uses: sergeysova/jq-action@v2
      id: index
      with:
        #cmd: 'jq .version package.json -r'
        cmd: 'jq -r ".project.dependencies.dependency | .[map(select(.artifactId == \"${{ inputs.artifactId }}\"))][0]" ./complete/file.json'
        multiline: true
   
    - name: Compare currentVersion vs desiredVersion
      uses: sergeysova/jq-action@v2
      id: currentVersion
      with:
        cmd: 'jq -r ".project.dependencies.dependency[${{ steps.index.outputs.value }}].version" ./complete/file.json'
    - name: Update version
      if: ${{ steps.currentVersion.outputs.value }} != ${{ inputs.desiredArtifactIdVersion }}
      id: updateVersion
      uses: sergeysova/jq-action@v2
      with:
        cmd: 'echo $(jq -r ".project.dependencies.dependency[${{ steps.index.outputs.value }}].version |= \"${{ inputs.desiredArtifactIdVersion }}\"" ./complete/file.json) > new.json'
    - name: Update POM
      uses: mikefarah/yq@master
      with:
        cmd: yq --input-format json --output-format xml new.json > ./complete/pom.xml

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update POM dependency version
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: main
        delete-branch: false
        title: '[Example] Update report'
        body: |
          Update report
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          automated pr
        assignees: daniel-lopez
        reviewers: daniel-lopez
        #team-reviewers: |
        #  developers
        #  qa-team
        #milestone: 1
        #draft: false

